export { default as AmbientAudioToggle } from "./AmbientAudioToggle";
export { default as Ded } from "./Ded";
export { default as Redirect } from "./Redirect";
export { default as About } from "./About";
export { default as Background } from "./Background";
export { default as Projects } from "./Projects";
export { default as Socials } from "./Socials";
export { default as LoadingSpinner } from "./LoadingSpinner";
export { default as Stars } from "./Stars";
